# Site settings
title: SimpleElastix
email: kaspermarstal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  SimpleElastix is a fork of SimpleITK that integrates the elastix 
  C++ image registration library. This makes state-of-the-art 
  medical image registration really easy to do in languages like 
  Python, Java, Ruby and R.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://simpleelastix.github.io" # the base hostname & protocol for your site
twitter_username: kaspermarstal
github_username:  kaspermarstal

# Build settings
markdown: kramdown
